math_flock:
  params:
    follow_cursor: false
    sensing_range: 100
    danger_range: 120
    initial_consensus: [800, 350]
    max_v: 5
    dt: 0.1
    distance: 40
  constants:
    c1_alpha: 3
    c1_beta: 20
    c1_gamma: 5
    c1_delta: 20

herding_apf:
  params:
    Cs: 1
    Cr: 1
    Cv: 1.5
    Co: 1.7
    distance_to_target: 120.0
    interagent_spacing: 150.0
    obstacle_range: 40.0
    sensing_range: 1000.0

    potential_func:
      edge_follow:
        attract: True
        repulse: True
        c: 8
        m: 2
      col_avoid:
        attract: True
        repulse: True
        c: 10
        m: 2
      obs_avoid:
        attract: True
        repulse: True
        c: 8
        m: 10

herding_cbf:
  params:
    max_u: 10
    min_robot_d: 140
    max_robot_d: 150
    min_animal_d: 120
    max_animal_d: 150
    collision_avoidance_d: 100
    converge_std: 10
    herding_target: [350, 350]
    coverage: 0.5
