animal:
  num: 1
  x_interval: [800, 900]
  y_interval: [200, 400]

robot:
  num: 1
  id: 10
  x_interval: [100, 200]
  y_interval: [300, 500]
  sensing_range: 1000.0
  comms_range: 100.0
  max_v: 10.0
  max_a: 10.0
