animal:
  num: 20
  x_interval: [800, 900]
  y_interval: [200, 400]

robot:
  num: 10
  id: 10
  x_interval: [100, 200]
  y_interval: [300, 500]
  sensing_range: 2000.0
  comms_range: 100.0
  max_v: 20.0
  max_a: 5.0
