animal:
  num: 20
  x_interval: [800, 900]
  y_interval: [300, 400]

robot:
  num: 4
  id: 10
  x_interval: [200, 210]
  y_interval: [200, 600]
  sensing_range: 200.0
  comms_range: 200.0
  max_v: 10.0
  max_a: 10.0
